// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List               = require("bs-platform/lib/js/list.js");
var $$Array            = require("bs-platform/lib/js/array.js");
var React              = require("react");
var ReasonReact        = require("reason-react/src/ReasonReact.js");
var Task$ReactTemplate = require("./Task.bs.js");

var component = ReasonReact.statelessComponent("TaskList");

function make(tasks, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var taskCards = List.map((function (task) {
              return ReasonReact.element(/* Some */[task[/* id */0]], /* None */0, Task$ReactTemplate.TaskCard[/* make */1](task, /* array */[]));
            }), tasks);
      return React.createElement("div", {
                  className: "tasklist"
                }, $$Array.of_list(taskCards));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
