// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React              = require("react");
var ReasonReact        = require("reason-react/src/ReasonReact.js");
var Util$ReactTemplate = require("./Util.bs.js");

var component = ReasonReact.statelessComponent("TaskCard");

function make(task, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "card"
                }, React.createElement("span", {
                      className: "id"
                    }, Util$ReactTemplate.str("Task "), React.createElement("em", undefined, Util$ReactTemplate.str(task[/* id */0]))), React.createElement("div", {
                      className: "dependencies"
                    }, Util$ReactTemplate.str("Dependencies go here")));
    });
  return newrecord;
}

var TaskCard = /* module */[
  /* component */component,
  /* make */make
];

exports.TaskCard = TaskCard;
/* component Not a pure module */
